
on:
  workflow_dispatch:
  push:
    branches:
        - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  scan_job:
    name: Boost Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: BoostSecurity Scanner
        uses: peaudecastor/boost-security-scanner-github@v2
        with:
          action: scan
          additional_args: --partial --project=DAVID-test-org-2/railsgoat
          api_endpoint: https://api.boostsecurity.dev
          api_token: ${{ secrets.BOOST_API_TOKEN_STAGE }}
  complete_scan:
    name: Complete Scan
    needs: [scan_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Complete Scan
        uses: peaudecastor/boost-security-scanner-github@v2
        with:
          action: complete
          api_endpoint: https://api.boostsecurity.dev
          api_token: ${{ secrets.BOOST_API_TOKEN_STAGE }}
